import os
import json
from google import genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv()

from asset_scraper import IngestionPipeline

def get_dynamic_asset_registry():
    try:
        pipeline = IngestionPipeline()
        assets = pipeline.get_all()
        registry = [a["asset_id"] for a in assets]
        return registry if registry else ["sofa", "coffee_table", "tv_unit", "plant", "armchair", "bookshelf", "rug"]
    except Exception as e:
        print(f"Failed to load dynamic registry: {e}")
        return ["sofa", "coffee_table", "tv_unit", "plant", "armchair", "bookshelf", "rug"]
# Initialize the modern google-genai client
_client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

def refine_prompt_with_groq(user_prompt: str) -> str:
    """Reads a user prompt (in Arabic or English), translates and expands it into a highly detailed English layout specification."""
    try:
        from groq import Groq
        groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
        
        system_prompt = (
            "You are an expert interior design AI assistant.\n"
            "Your job is to read a user's room design prompt (which may be in Arabic or English) and convert it into a highly detailed, professional, structured design specification in English.\n\n"
            "Guidelines:\n"
            "1. Translate any Arabic request to English.\n"
            "2. Expand the design logically: specify exact furniture items, color choices (following the 60-30-10 rule: 60% dominant neutral wall/floor, 30% furniture, 10% accents), lighting mood, and relative spatial layout (e.g. coffee table in front of sofa, TV unit opposite the sofa).\n"
            "3. Limit the items to our allowed asset registry: sofa, coffee_table, tv_unit, plant, armchair, bookshelf, rug, window.\n"
            "4. Describe the color palette in Hex codes so the executor can apply it precisely.\n"
            "5. Do NOT output any code or JSON. Just output a clean, descriptive paragraph in English describing the layout, dimensions, colors, and positioning details for the generator."
        )
        
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.7,
            max_tokens=1000
        )
        refined_prompt = response.choices[0].message.content.strip()
        print(f"Refined prompt generated by Groq: {refined_prompt}")
        return refined_prompt
    except Exception as e:
        print(f"Failed to refine prompt with Groq: {e}. Using original user prompt.")
        return user_prompt

# Global RagRetriever instance
_retriever_instance = None

def get_retriever():
    global _retriever_instance
    if _retriever_instance is None:
        try:
            from rag_retriever import RagRetriever
            _retriever_instance = RagRetriever()
        except Exception as e:
            print(f"[RAG] Failed to initialize RagRetriever: {e}")
            _retriever_instance = False # Use False to indicate failure and avoid retrying
    return _retriever_instance

def generate_layout(prompt: str, image_b64: str | None = None, schema_path: str = "schema.json") -> dict:
    """Uses Gemini to generate a 3D scene payload adhering to the schema, with optional multimodal vision input."""
    with open(schema_path, "r", encoding='utf-8') as f:
        schema = json.load(f)

    # Refine prompt using Groq (translates Arabic, enriches design context, saves tokens/load on Gemini)
    refined_prompt = refine_prompt_with_groq(prompt)

    asset_registry = get_dynamic_asset_registry()
    system_instruction = (
        "You are an expert interior design AI architect and a strict 3D mathematician. "
        "Your job is to read user prompts and design a 3D room layout matching their request. "
        "Generate a valid JSON object strictly adhering to the provided JSON Schema.\n"
        "MULTIMODAL VISION TASK: If an image is provided in the prompt, you MUST visually analyze the room type, style, and furniture placement. "
        "Estimate the physical size of the room in meters (Width and Depth) and add a `room_dimensions` object to the root JSON. "
        "Match the identified furniture with the closest available `asset_id`s in our catalog. "
        "Calculate logical `position` [x, 0, z] coordinates mapping the 2D image layout into our 3D grid as accurately as possible.\n\n"
        "### STRICT ARCHITECTURAL CONSTRAINTS:\n"
        "1. REALISTIC ROOM SIZE: Default to smaller, cozy room dimensions (e.g., 5x5 or 4x5 meters) instead of massive spaces, unless the user explicitly asks for a huge hall. "
        "The floor must be 5x5x0.1 located at (t_x: 0, t_y: 0, t_z: 0). "
        "The scene MUST be a 'Diorama' (an open stage). ALWAYS generate exactly 2 walls at the back perimeters to frame the scene (e.g., North wall at z=-2.5, West wall at x=-2.5). "
        "NEVER enclose the room fully. ALWAYS leave the front (South z=2.5 and East x=2.5) completely open for the isometric camera to view inside.\n"
        "2. ORIGIN & COORDINATES: The origin (0,0,0) is the CENTER of the room. A 5x5 floor goes from X=-2.5 to X=2.5, and Z=-2.5 to Z=2.5.\n"
        "3. STRICT SPATIAL BOUNDARIES (CRITICAL): ALL generated objects (furniture, plants, etc.) MUST have their `[t_x, t_z]` coordinates strictly inside the room's dimensions. For a 5x5 floor, NO object can have an X or Z coordinate < -2.5 or > 2.5 (e.g., t_x = -4.0 is FORBIDDEN and out-of-bounds). Do not let any object float outside the floor grid.\n"
        "3. FLOOR ANCHOR & Z POSITION: All objects MUST have transform.t_y = 0. Never place objects in the air or below the floor. "
        "Their Z position (which in Blender is the vertical axis, corresponding to t_y = 0 in the JSON payload) must be strictly >= 0 (resting on the floor).\n"
        "4. WALL PLACEMENT: NEVER place walls across the center. A wall along the X axis (length=5) should have Z=-2.5. A wall along the Z axis (width=5) should have X=-2.5.\n"
        "5. WALL SNAPPING & CLIPPING PREVENTION: Objects like TV units, cabinets, bookshelves, or beds MUST have their back edge perfectly aligned flush with a perimeter wall. "
        "They must NOT intersect or clip through the wall boundaries. For example, if a wall of thickness (width) W_w is at Z = Z_w, the inner surface of the wall is at Z_inner = Z_w + W_w/2. "
        "For an object of depth (width) W_o aligned flush with this wall, its center Z must be located at Z_inner + W_o/2 (i.e., Z = Z_w + W_w/2 + W_o/2). "
        "If wall is at Z = -2.5 (width 0.2) and object width is 0.4, center Z = -2.5 + 0.1 + 0.2 = -2.2. Any other value (like -2.3 or -2.4) causes clipping and is strictly prohibited.\n"
        "6. DYNAMIC WINDOW MESH (CRITICAL): You MUST generate exactly ONE large, floor-to-ceiling architectural window mesh on one of the main walls. Its `type` must be `\"window\"`. Position it flush against or slightly cutting into one of the walls (e.g. if wall is at Z=-2.5, place window at Z=-2.49). Make it wide and tall (e.g., length: 3.0, width: 0.2, height: 2.5) to let natural light in.\n"
        "7. FURNITURE GROUPING & SPACING (CRITICAL): Furniture MUST face the correct logical direction using `transform.yaw_y` (0, 90, 180, -90 degrees). You MUST group related items but KEEP THEM SPACED OUT. A TV unit and a sofa should be at least 3 meters apart (e.g., Sofa at Z=-1.5, TV at Z=1.5). Do NOT clump them at the center (0,0).\n"
        f"8. STRICT ASSET REGISTRY & COLLISION PREVENTION: For 'furniture', you MUST provide an `asset_id` strictly chosen from this list: {json.dumps(asset_registry)}. You MUST use spatial math to avoid overlapping. No two pieces of furniture should share the exact same [t_x, t_z] coordinates (except a rug which goes under furniture). Provide at least 0.5m buffer between adjacent chairs/tables.\n"
        "9. MASTER COLOR THEORY & CONTRAST (CRITICAL): Act as a Master Interior Designer. Define a harmonious architectural palette at the root level using `wall_color` and `floor_color`. Apply the 60-30-10 Rule: 60% dominant neutral colors (walls/floor), 30% secondary contrasting colors (main furniture like sofas/tables), and 10% accent colors (chairs, plants, rugs). STRICT CONTRAST RULE: The furniture MUST NOT blend into the floor or walls. If the floor is light wood, the sofa or rug MUST be a darker or distinct color (e.g., Navy blue, Emerald green, or Dark Grey) to create visual depth. Ensure the generated palette 'pops' with beautiful contrast.\n"
        "10. INTELLIGENT DETAILING & FILLERS (PROACTIVE DESIGN): Do not be a literal command executor. Be a proactive Interior Designer. Even if the user asks for a simple room, YOU MUST intelligently add logical, non-intrusive filler objects from the asset registry to complete the scene (e.g., add a `plant` in an empty corner, add a `rug` under the coffee table, add an `armchair` at a slight angle near the sofa).\n"
        "11. COZY GROUPING: Group furniture to create conversational and functional zones. Objects should be clustered naturally (e.g., place a plant right next to the TV stand, not in a random distant corner).\n"
        "12. SMART ECONOMY (CRITICAL): For EVERY 'furniture' object, you MUST include an 'economy' object conforming to the schema. Generate realistic retail prices for the Saudi market (currency: 'SAR'). Determine the brand based on style: basic/modern = IKEA (SAR 100-2500), contemporary = Abyat (SAR 1500-4500), luxury = West Elm (SAR 4000+). Generate a realistic dummy `store_url` matching the brand, and a random `sku`.\n\n"
        "### ONE-SHOT PERFECT EXAMPLE (5x5 Cozy Room):\n"
        "```json\n"
        "{\n"
        "  \"stage\": 1,\n"
        "  \"wall_color\": \"#E8E5DF\",\n"
        "  \"floor_color\": \"#A48E74\",\n"
        "  \"room_dimensions\": {\n"
        "    \"width\": 5,\n"
        "    \"depth\": 5\n"
        "  },\n"
        "  \"objects\": [\n"
        "    {\n"
        "      \"id\": \"tv_unit_main\",\n"
        "      \"type\": \"furniture\",\n"
        "      \"asset_id\": \"tv_unit\",\n"
        "      \"hex_color\": \"#1A1A1A\",\n"
        "      \"dimensions\": {\"length\": 1.5, \"width\": 0.4, \"height\": 0.6},\n"
        "      \"transform\": {\"t_x\": 0, \"t_y\": 0, \"t_z\": 1.5, \"yaw_y\": 180, \"scale\": 1.0},\n"
        "      \"economy\": {\"price\": 850, \"currency\": \"SAR\", \"store_url\": \"https://www.ikea.com/sa/en/p/besta\", \"brand\": \"IKEA\", \"sku\": \"302.945.05\"}\n"
        "    },\n"
        "    {\n"
        "      \"id\": \"sofa_main\",\n"
        "      \"type\": \"furniture\",\n"
        "      \"asset_id\": \"sofa\",\n"
        "      \"hex_color\": \"#0060ac\",\n"
        "      \"dimensions\": {\"length\": 2.2, \"width\": 0.9, \"height\": 0.8},\n"
        "      \"transform\": {\"t_x\": 0, \"t_y\": 0, \"t_z\": -1.5, \"yaw_y\": 0, \"scale\": 1.0},\n"
        "      \"economy\": {\"price\": 5400, \"currency\": \"SAR\", \"store_url\": \"https://www.westelm.com.sa/en/p/harmony-sofa\", \"brand\": \"West Elm\", \"sku\": \"WE-8832\"}\n"
        "    },\n"
        "    {\n"
        "      \"id\": \"armchair_side\",\n"
        "      \"type\": \"furniture\",\n"
        "      \"asset_id\": \"armchair\",\n"
        "      \"hex_color\": \"#E5A93C\",\n"
        "      \"dimensions\": {\"length\": 0.8, \"width\": 0.8, \"height\": 0.9},\n"
        "      \"transform\": {\"t_x\": 1.5, \"t_y\": 0, \"t_z\": -1.0, \"yaw_y\": -45, \"scale\": 1.0},\n"
        "      \"economy\": {\"price\": 1400, \"currency\": \"SAR\", \"store_url\": \"https://www.abyat.com/sa/en/armchair\", \"brand\": \"Abyat\", \"sku\": \"AB-882\"}\n"
        "    },\n"
        "    {\n"
        "      \"id\": \"coffee_table\",\n"
        "      \"type\": \"furniture\",\n"
        "      \"asset_id\": \"coffee_table\",\n"
        "      \"hex_color\": \"#8B4513\",\n"
        "      \"dimensions\": {\"length\": 1.0, \"width\": 0.6, \"height\": 0.4},\n"
        "      \"transform\": {\"t_x\": 0, \"t_y\": 0, \"t_z\": -0.5, \"yaw_y\": 0, \"scale\": 1.0},\n"
        "      \"economy\": {\"price\": 1200, \"currency\": \"SAR\", \"store_url\": \"https://www.abyat.com/sa/en/coffee-table-valen\", \"brand\": \"Abyat\", \"sku\": \"AB-1102\"}\n"
        "    },\n"
        "    {\n"
        "      \"id\": \"rug_main\",\n"
        "      \"type\": \"furniture\",\n"
        "      \"asset_id\": \"rug\",\n"
        "      \"hex_color\": \"#D3C5B5\",\n"
        "      \"dimensions\": {\"length\": 2.5, \"width\": 1.5, \"height\": 0.02},\n"
        "      \"transform\": {\"t_x\": 0, \"t_y\": 0, \"t_z\": 0.0, \"yaw_y\": 0, \"scale\": 1.0},\n"
        "      \"economy\": {\"price\": 450, \"currency\": \"SAR\", \"store_url\": \"https://www.ikea.com/sa/en/p/stoense-rug\", \"brand\": \"IKEA\", \"sku\": \"104.268.04\"}\n"
        "    },\n"
        "    {\n"
        "      \"id\": \"plant_corner\",\n"
        "      \"type\": \"furniture\",\n"
        "      \"asset_id\": \"plant\",\n"
        "      \"hex_color\": \"#2E8B57\",\n"
        "      \"dimensions\": {\"length\": 0.6, \"width\": 0.6, \"height\": 1.5},\n"
        "      \"transform\": {\"t_x\": -2.0, \"t_y\": 0, \"t_z\": 1.5, \"yaw_y\": 0, \"scale\": 1.0},\n"
        "      \"economy\": {\"price\": 220, \"currency\": \"SAR\", \"store_url\": \"https://www.ikea.com/sa/en/p/fejka-artificial\", \"brand\": \"IKEA\", \"sku\": \"404.339.42\"}\n"
        "    }\n"
        "  ]\n"
        "}\n"
        "```\n\n"
        f"### JSON SCHEMA:\n{json.dumps(schema, indent=2)}"
    )

    contents = [refined_prompt]
    if image_b64:
        import base64
        try:
            if "," in image_b64:
                mime_type = image_b64.split(";")[0].split(":")[1]
                data = image_b64.split(",")[1]
            else:
                mime_type = "image/jpeg"
                data = image_b64
            
            image_bytes = base64.b64decode(data)
            contents.append(types.Part.from_bytes(data=image_bytes, mime_type=mime_type))
            print(f"Added multimodal image to Gemini payload (mime_type: {mime_type})")
        except Exception as e:
            print(f"Failed to parse image Base64: {e}")

    try:
        response = _client.models.generate_content(
            model="gemini-2.5-flash",
            contents=contents,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                response_mime_type="application/json",
            ),
        )
        response_text = response.text
    except Exception as gemini_err:
        print(f"Gemini API failed ({gemini_err}). Falling back to Groq...")
        try:
            from groq import Groq
            groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
            groq_response = groq_client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {"role": "system", "content": system_instruction},
                    {"role": "user", "content": refined_prompt}
                ],
                temperature=0.7,
                max_tokens=4000,
                response_format={"type": "json_object"}
            )
            response_text = groq_response.choices[0].message.content
        except Exception as groq_err:
            print(f"Groq fallback also failed: {groq_err}")
            raise RuntimeError(f"Both primary (Gemini) and fallback (Groq) models failed. Gemini Error: {gemini_err}") from groq_err

    try:
        text = response_text.strip()
        if text.startswith("```json"):
            text = text[7:]
        elif text.startswith("```"):
            text = text[3:]
        if text.endswith("```"):
            text = text[:-3]
        payload = json.loads(text.strip())
        
        # Enrich with real IKEA data using RAG
        try:
            retriever = get_retriever()
            if retriever and "objects" in payload:
                for obj in payload["objects"]:
                    if obj.get("type") == "furniture":
                        color = obj.get("hex_color", "")
                        asset_id = obj.get("asset_id", "")
                        query = f"IKEA {color} {asset_id}"
                        results = retriever.search(query, limit=1)
                        if results:
                            best = results[0]
                            obj["economy"] = {
                                "price": float(best["price"]),
                                "currency": "SAR",
                                "store_url": best["link"],
                                "brand": "IKEA",
                                "sku": best["item_id"],
                                "name": best["name"]
                            }
                            # The frontend expects dimensions in meters (X=length, Y=height, Z=width/depth)
                            # CSV dimensions are in mm.
                            if best["dim_width"] > 0 and best["dim_height"] > 0 and best["dim_depth"] > 0:
                                obj["dimensions"] = {
                                    "length": best["dim_width"] / 1000.0,
                                    "height": best["dim_height"] / 1000.0,
                                    "width": best["dim_depth"] / 1000.0
                                }
        except Exception as rag_e:
            print(f"[RAG] Failed to enrich payload: {rag_e}")
            
        return payload
    except Exception as e:
        print(f"Failed to parse LLM response: {response_text}")
        raise e
