import { SceneItem } from "./useSceneStore";

export type TemplateType = "LivingRoom" | "Bedroom" | "Kitchen";

const LOCAL_GLB = {
  sofra:   "/assets/sofa.glb",
  armchair: "/assets/armchair.glb",
  table:   "/assets/table.glb",
  tv_unit: "/assets/tv_unit.glb",
  rug:     "/assets/rug.glb",
  plant:   "/assets/plant.glb",
  deck_chair:     "/assets/deck_chair.glb",
  dining_chair:   "/assets/dining_chair.glb",
  drawer_cabinet: "/assets/drawer_cabinet.glb",
  coffee_table_art:  "/assets/coffee_table_art.glb",
  display_shelf:  "/assets/display_shelf.glb",
  coffee_table_round: "/assets/coffee_table_round.glb",
  armchair_wood:  "/assets/armchair_wood.glb",
  outdoor_set:    "/assets/outdoor_set.glb",
  sofa_khronos:   "/assets/sofa_khronos.glb",
  vase_flowers:   "/assets/vase_flowers.glb",
  camera_antique:  "/assets/camera_antique.glb",
};

export const PREDEFINED_TEMPLATES: Record<TemplateType, Omit<SceneItem, 'addedAt'>[]> = {
  LivingRoom: [
    {
      id: "kivik_sofa",
      name: "أريكة 3 مقاعد KIVIK",
      brand: "IKEA",
      price: 2495,
      currency: "SAR",
      category: "seating",
      modelUrl: LOCAL_GLB.sofra,
      dimensions: { width: 2280, height: 830, depth: 950 },
      thumbnailUrl: "",
      instanceId: "",
      position: [0, 0, -1.5],
      rotation: [0, 0, 0],
    },
    {
      id: "coffee_table_art",
      name: "طاولة قهوة مودرن",
      brand: "Rwaq",
      price: 0,
      currency: "SAR",
      category: "tables",
      modelUrl: LOCAL_GLB.coffee_table_art,
      dimensions: { width: 1000, height: 450, depth: 600 },
      thumbnailUrl: "",
      instanceId: "",
      position: [0, 0, 0.2],
      rotation: [0, 0, 0],
    },
    {
      id: "lohals_rug",
      name: "سجادة جوت مسطحة LOHALS",
      brand: "IKEA",
      price: 395,
      currency: "SAR",
      category: "rugs",
      modelUrl: LOCAL_GLB.rug,
      dimensions: { width: 1600, height: 5, depth: 2300 },
      thumbnailUrl: "",
      instanceId: "",
      position: [0, 0.02, -0.5],
      rotation: [0, 0, 0],
    },
    {
      id: "armchair_wood",
      name: "كرسي بذراعين خشب",
      brand: "Rwaq",
      price: 0,
      currency: "SAR",
      category: "seating",
      modelUrl: LOCAL_GLB.armchair_wood,
      dimensions: { width: 700, height: 950, depth: 750 },
      thumbnailUrl: "",
      instanceId: "",
      position: [2.2, 0, -1.5],
      rotation: [0, -Math.PI / 6, 0],
    },
    {
      id: "display_shelf",
      name: "رف عرض",
      brand: "Rwaq",
      price: 0,
      currency: "SAR",
      category: "storage",
      modelUrl: LOCAL_GLB.display_shelf,
      dimensions: { width: 800, height: 1200, depth: 300 },
      thumbnailUrl: "",
      instanceId: "",
      position: [-2.5, 0, 0.5],
      rotation: [0, Math.PI / 2, 0],
    },
    {
      id: "plant_potted",
      name: "نبات داخلي",
      brand: "IKEA",
      price: 145,
      currency: "SAR",
      category: "decor",
      modelUrl: LOCAL_GLB.plant,
      dimensions: { width: 350, height: 900, depth: 350 },
      thumbnailUrl: "",
      instanceId: "",
      position: [-2.5, 0, -1.8],
      rotation: [0, 0, 0],
    },
  ],
  Bedroom: [
    {
      id: "strandmon_chair",
      name: "كرسي بمسندين STRANDMON",
      brand: "IKEA",
      price: 1195,
      currency: "SAR",
      category: "seating",
      modelUrl: LOCAL_GLB.armchair,
      dimensions: { width: 820, height: 1010, depth: 960 },
      thumbnailUrl: "",
      instanceId: "",
      position: [1.5, 0, -1.5],
      rotation: [0, -Math.PI / 4, 0],
    },
    {
      id: "drawer_cabinet",
      name: "خزانة أدراج",
      brand: "Rwaq",
      price: 0,
      currency: "SAR",
      category: "storage",
      modelUrl: LOCAL_GLB.drawer_cabinet,
      dimensions: { width: 600, height: 800, depth: 400 },
      thumbnailUrl: "",
      instanceId: "",
      position: [-1.8, 0, 0.5],
      rotation: [0, Math.PI / 3, 0],
    },
    {
      id: "lohals_rug",
      name: "سجادة جوت مسطحة LOHALS",
      brand: "IKEA",
      price: 395,
      currency: "SAR",
      category: "rugs",
      modelUrl: LOCAL_GLB.rug,
      dimensions: { width: 1600, height: 5, depth: 2300 },
      thumbnailUrl: "",
      instanceId: "",
      position: [0, 0.02, 0],
      rotation: [0, 0, 0],
    },
    {
      id: "vase_flowers",
      name: "مزهرية",
      brand: "Rwaq",
      price: 0,
      currency: "SAR",
      category: "decor",
      modelUrl: LOCAL_GLB.vase_flowers,
      dimensions: { width: 150, height: 350, depth: 150 },
      thumbnailUrl: "",
      instanceId: "",
      position: [0.5, 0, -1.2],
      rotation: [0, 0, 0],
    },
    {
      id: "camera_antique",
      name: "كاميرا",
      brand: "Rwaq",
      price: 0,
      currency: "SAR",
      category: "decor",
      modelUrl: LOCAL_GLB.camera_antique,
      dimensions: { width: 200, height: 300, depth: 150 },
      thumbnailUrl: "",
      instanceId: "",
      position: [-1.5, 0, -1.5],
      rotation: [0, Math.PI / 2, 0],
    },
  ],
  Kitchen: [
    {
      id: "outdoor_set",
      name: "طقم حديقة",
      brand: "Rwaq",
      price: 0,
      currency: "SAR",
      category: "tables",
      modelUrl: LOCAL_GLB.outdoor_set,
      dimensions: { width: 1500, height: 750, depth: 1500 },
      thumbnailUrl: "",
      instanceId: "",
      position: [0, 0, 0],
      rotation: [0, 0, 0],
    },
    {
      id: "dining_chair",
      name: "كرسي طعام",
      brand: "Rwaq",
      price: 0,
      currency: "SAR",
      category: "seating",
      modelUrl: LOCAL_GLB.dining_chair,
      dimensions: { width: 450, height: 850, depth: 500 },
      thumbnailUrl: "",
      instanceId: "",
      position: [-1.2, 0, 0.2],
      rotation: [0, Math.PI / 2, 0],
    },
    {
      id: "dining_chair_2",
      name: "كرسي طعام",
      brand: "Rwaq",
      price: 0,
      currency: "SAR",
      category: "seating",
      modelUrl: LOCAL_GLB.dining_chair,
      dimensions: { width: 450, height: 850, depth: 500 },
      thumbnailUrl: "",
      instanceId: "",
      position: [1.2, 0, -0.2],
      rotation: [0, -Math.PI / 2, 0],
    },
    {
      id: "deck_chair",
      name: "كرسي سطح",
      brand: "Rwaq",
      price: 0,
      currency: "SAR",
      category: "seating",
      modelUrl: LOCAL_GLB.deck_chair,
      dimensions: { width: 580, height: 900, depth: 600 },
      thumbnailUrl: "",
      instanceId: "",
      position: [-2, 0, 1.5],
      rotation: [0, Math.PI / 4, 0],
    },
    {
      id: "plant_potted",
      name: "نبات داخلي",
      brand: "IKEA",
      price: 145,
      currency: "SAR",
      category: "decor",
      modelUrl: LOCAL_GLB.plant,
      dimensions: { width: 350, height: 900, depth: 350 },
      thumbnailUrl: "",
      instanceId: "",
      position: [2, 0, 1.2],
      rotation: [0, 0, 0],
    },
  ]
};
